name: Release

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main-dev"]


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  ARTIFACTORY_NAME: artifactory


jobs:

  build:

    name: Build ustore
    runs-on: ubuntu-latest
    steps:
    - name: Install dependences
      run: |
        sudo apt-get update -y
        sudo apt-get install -y apt-utils 2>&1 | grep -v "debconf: delaying package configuration, since apt-utils is not installed"
        sudo apt-get install -y --no-install-recommends git cmake libssl-dev build-essential zlib1g zlib1g-dev python3 python3-dev python3-pip 
    
    - uses: actions/checkout@v3

    - name: Get Conan
      run: pip3 install conan==1.57.0
      
    - name: Create default profile
      run: conan profile new --detect default
      
    - name: Update profile
      run: conan profile update settings.compiler.libcxx=libstdc++11 default
      
    - name: Install dependencies
      env:
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      run: |
        conan remote add artifactory http://54.163.51.0:8081/artifactory/api/conan/conan-local
        conan user $ARTIFACTORY_USERNAME -r $ARTIFACTORY_NAME -p $ARTIFACTORY_PASSWORD
        conan install ustore/1.0.0@demo/stable -r $ARTIFACTORY_NAME -g cmake
            
    - name: Build and Make
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DUSTORE_BUILD_TESTS=0 \
              -DUSTORE_BUILD_BENCHMARKS=0 \
              -DUSTORE_BUILD_ENGINE_UCSET=1 \
              -DUSTORE_BUILD_ENGINE_LEVELDB=1 \
              -DUSTORE_BUILD_ENGINE_ROCKSDB=1 \
              -DUSTORE_BUILD_API_FLIGHT_CLIENT=0 \
              -DUSTORE_BUILD_API_FLIGHT_SERVER=1 . \
              -B ./build_release
        
        make -j32 \
             ustore_flight_server_ucset \
             ustore_flight_server_leveldb \
             ustore_flight_server_rocksdb \
             --silent \
             -C ./build_release
    
    - name: Upload Binaries
      uses: actions/upload-artifact@v3.1.1
      with:
        name: binaries
        path: build_release/bin/*

  
  #  test:
  #   runs-on: ubuntu-20.04
  #   needs: build

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Download a Build Artifact
  #       uses: actions/download-artifact@v3.0.1
  #       with:
  #         name: binaries

  #     - name: Change Permissions
  #       run: chmod +x /home/runner/work/conan-ustore-ci/conan-ustore-ci/*
      
  #     - name: Run Tests
  #       run: for test in $(ls /home/runner/work/conan-ustore-ci/conan-ustore-ci/*unit_test); do  echo -e "------ \e[93mRunning $test\e[0m ------"; timeout -v --kill-after=5 300 $test; done
