name: Release

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main-dev"]


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write


jobs:

  build:

    name: Build ustore
    runs-on: ubuntu-latest
    steps:
    - name: Install dependences
      run: |
        sudo apt-get update -y
        sudo apt-get install -y apt-utils 2>&1 | grep -v "debconf: delaying package configuration, since apt-utils is not installed"
        sudo apt-get install -y --no-install-recommends cmake git libssl-dev build-essential zlib1g zlib1g-dev python3 python3-dev
    
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.57.0

    - name: Create default Conan profile
      run: conan profile new default --detect

    - name: Conan profile update
      run:  conan profile update settings.compiler.libcxx=libstdc++11 default
    
    - name: Show files
      run:  ls

    - name: Install dependences for ustore
      run:  |
            conan install /home/runner/work/conan-ustore-ci/conan-ustore-ci/conanfile.py \
            --build=missing \
            --install-folder="cmake" \
            -s compiler.libcxx=libstdc++11
    
    - name: Build ustore
      run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DUSTORE_BUILD_TESTS=0 \
          -DUSTORE_BUILD_BENCHMARKS=0 \
          -DUSTORE_BUILD_ENGINE_UCSET=1 \
          -DUSTORE_BUILD_ENGINE_LEVELDB=1 \
          -DUSTORE_BUILD_ENGINE_ROCKSDB=1 \ 
          -DUSTORE_BUILD_API_FLIGHT_CLIENT=0 \
          -DUSTORE_BUILD_API_FLIGHT_SERVER=1 . \
          -B ./build_release && 
          make -j32 \
            ustore_flight_server_ucset \
            ustore_flight_server_leveldb \
            ustore_flight_server_rocksdb \
            --silent \
            -C ./build_release