name: Release

on:
  push:
    branches: ["main-dev"]

env:
  BUILD_TYPE: Release
  ARTIFACTORY_NAME: artifactory
  ARTIFACTORY_USERNAME: admin
  INSTANCE_ID: i-08c772cfd944ae53b
  AWS_DEFAULT_REGION: us-east-1


jobs:
  build:
    name: Build ustore
    runs-on: ubuntu-latest
    steps:
    - name: Install dependences
      run: |
        sudo apt-get update -y
        sudo apt-get install -y apt-utils 2>&1 | grep -v "debconf: delaying package configuration, since apt-utils is not installed"
        sudo apt-get install -y --no-install-recommends git cmake libssl-dev build-essential zlib1g zlib1g-dev python3 python3-dev python3-pip 
    
    - uses: actions/checkout@v3
    
    - name: Install AWS CLI v2
      run:  |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/
        
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region $AWS_DEFAULT_REGION
    
    - name: Start artifactory instance
      id: ip
      run: |
        aws ec2 start-instances --instance-ids $INSTANCE_ID
        sleep 60
        echo "public_ip=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)" >> $GITHUB_OUTPUT
        
    - name: Install Conan
      run: pip install conan==1.57.0
      
    - name: Create conan default profile
      run: conan profile new --detect default
      
    - name: Update conan profile
      run: conan profile update settings.compiler.libcxx=libstdc++11 default
      
    - name: Install ustore dependencies using conan
      run: |
        conan remote add $ARTIFACTORY_NAME http://${{ steps.ip.outputs.public_ip }}:8081/artifactory/api/conan/conan-local
        conan user $ARTIFACTORY_USERNAME -r $ARTIFACTORY_NAME -p ${{ secrets.ARTIFACTORY_PASSWORD }}
        conan install ustore/1.0.0@demo/stable -r $ARTIFACTORY_NAME -g cmake
        
    - name: Stop artifactory instance
      run: aws ec2 stop-instances --instance-ids $INSTANCE_ID 
            
    - name: Configure cmake
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DUSTORE_BUILD_TESTS=0 \
              -DUSTORE_BUILD_BENCHMARKS=0 \
              -DUSTORE_BUILD_ENGINE_UCSET=1 \
              -DUSTORE_BUILD_ENGINE_LEVELDB=1 \
              -DUSTORE_BUILD_ENGINE_ROCKSDB=1 \
              -DUSTORE_BUILD_API_FLIGHT_CLIENT=0 \
              -DUSTORE_BUILD_API_FLIGHT_SERVER=1 . \
              -B ./build_release
              
    - name: Build   
      run: |
        make -j4 \
             ustore_flight_server_ucset \
             ustore_flight_server_leveldb \
             ustore_flight_server_rocksdb \
             --silent \
             -C ./build_release
    
    - name: Upload Binaries
      uses: actions/upload-artifact@v3.1.1
      with:
        name: binaries
        path: build_release/bin/*